13 album GUI
joshua-lehmann/ImageMetaManager pull request #14
Opened 2023-02-04 10:52 UTC by joshua-lehmann

2023-02-04 11:31 UTC, theGreyPilgrim42 requested changes
The primary view looks good to me.
I think we should add the logs and src/test/resoures to gitignore though.

And two questions concerning the primary view:
- Should the album id be visible in the gui (currently it isn't)? Personally I don't think it has to be visible, so we could remove it from the createAlbumPane() method.
- Are we restricted to a max. of 20 Albums because of the current grid layout? If so, do we care? I think for the sake of this project the restriction would be okay because being able to save a certain amount of albums was not defined in our "Szenarien-Beschrieb".

2023-02-04 11:50 UTC, joshua-lehmann commented
> The primary view looks good to me. I think we should add the logs and src/test/resoures to gitignore though.
> 
> And two questions concerning the primary view:
> 
> * Should the album id be visible in the gui (currently it isn't)? Personally I don't think it has to be visible, so we could remove it from the createAlbumPane() method.
> * Are we restricted to a max. of 20 Albums because of the current grid layout? If so, do we care? I think for the sake of this project the restriction would be okay because being able to save a certain amount of albums was not defined in our "Szenarien-Beschrieb".

I added the logs to the git ignore. The resources I would like to keep, since I use the images for the tests, so they need to be in the repo. However the storage can be excluded.

The id is not visible and I also think it should not be visible. I actually just put it there, so that we can later use it to get the album and send it to the album page. It think it is better to get it by ID instead of getting it by the name. So I will later change that.

For the grid I think we can start with a fixed layout/number of items. If we have time we can implement a scroll view where you can have as many albums displayed as you want. For now the grid and the dynamic placement of the albums is not yet finished/working correctly. I will add this later in a different branch.

2023-02-06 19:12 UTC, theGreyPilgrim42 approved these changes

2023-02-06 19:13 UTC, merged

2023-02-14 11:47 UTC, joshua-lehmann commented
closes #13